export const nodes = [
        {"id": "Fantine", "group": 3},
        {"id": "Pontmercy", "group": 3},
        {"id": "Dahlia", "group": 1},
        {"id": "Zephine", "group": 1},
        {"id": "Tholomyes", "group": 1},
        {"id": "Listolier", "group": 1},
        {"id": "Fameuil", "group": 1},
        {"id": "Blacheville", "group": 1},
        {"id": "Favourite", "group": 1},
        {"id": "Marguerite", "group": 1},
        {"id": "Brujon", "group": 1},
        {"id": "Toussaint", "group": 1},
        {"id": "Montparnasse", "group": 1},
        {"id": "Claquesous", "group": 1},
        {"id": "Gueulemer", "group": 1},
        {"id": "Joly", "group": 1},
        {"id": "Courfeyrac", "group": 1},
        {"id": "Prouvaire", "group": 1},
        {"id": "Enjolras", "group": 1},
        {"id": "Jondrette", "group": 1},
        {"id": "Marius", "group": 1},
        {"id": "Boulatruelle", "group": 1},
        {"id": "Bamatabois", "group": 1},
      ]

export const links = [
  {"source": "Fantine", "target": "Dahlia", "value": 0.25},
  {"source": "Fantine", "target": "Zephine", "value": 0.25},
  {"source": "Fantine", "target": "Tholomyes", "value": 0.25},
  {"source": "Fantine", "target": "Listolier", "value": 0.25},
  {"source": "Fantine", "target": "Fameuil", "value": 0.25},
  {"source": "Fantine", "target": "Blacheville", "value": 0.25},
  {"source": "Fantine", "target": "Favourite", "value": 0.25},
  {"source": "Fantine", "target": "Marguerite", "value": 0.25},
  {"source": "Fantine", "target": "Brujon", "value": 0.25},
  {"source": "Fantine", "target": "Toussaint", "value": 0.25},
  {"source": "Fantine", "target": "Montparnasse", "value": 0.25},
  {"source": "Fantine", "target": "Claquesous", "value": 0.25},
  {"source": "Fantine", "target": "Gueulemer", "value": 0.25},
  {"source": "Fantine", "target": "Joly", "value": 0.25},
  {"source": "Fantine", "target": "Courfeyrac", "value": 0.25},
  {"source": "Fantine", "target": "Prouvaire", "value": 0.25},
  {"source": "Fantine", "target": "Enjolras", "value": 0.25},
  {"source": "Fantine", "target": "Jondrette", "value": 0.25},
  {"source": "Fantine", "target": "Marius", "value": 0.25},
  {"source": "Fantine", "target": "Boulatruelle", "value": 0.25},
  {"source": "Fantine", "target": "Bamatabois", "value": 0.25},
  {"source": "Pontmercy", "target": "Dahlia", "value": 0.25},
  {"source": "Pontmercy", "target": "Zephine", "value": 0.25},
  {"source": "Pontmercy", "target": "Tholomyes", "value": 0.25},
  {"source": "Pontmercy", "target": "Listolier", "value": 0.25},
  {"source": "Pontmercy", "target": "Fameuil", "value": 0.25},
  {"source": "Pontmercy", "target": "Blacheville", "value": 0.25},
  {"source": "Pontmercy", "target": "Favourite", "value": 0.25},
  {"source": "Pontmercy", "target": "Marguerite", "value": 0.25},
  {"source": "Pontmercy", "target": "Brujon", "value": 0.25},
  {"source": "Pontmercy", "target": "Toussaint", "value": 0.25},
  {"source": "Pontmercy", "target": "Montparnasse", "value": 0.25},
  {"source": "Pontmercy", "target": "Claquesous", "value": 0.25},
  {"source": "Pontmercy", "target": "Gueulemer", "value": 0.25},
  {"source": "Pontmercy", "target": "Joly", "value": 0.25},
  {"source": "Pontmercy", "target": "Courfeyrac", "value": 0.25},
  {"source": "Pontmercy", "target": "Prouvaire", "value": 0.25},
  {"source": "Pontmercy", "target": "Enjolras", "value": 0.25},
  {"source": "Pontmercy", "target": "Jondrette", "value": 0.25},
  {"source": "Pontmercy", "target": "Marius", "value": 0.25},
  {"source": "Pontmercy", "target": "Boulatruelle", "value": 0.25},
  {"source": "Pontmercy", "target": "Bamatabois", "value": 0.25},
  
]
